M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu24.04.1} date 2024-09-24T16:48:20+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-24T16:48:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.7162Y-4.9693
X5.9438Y-4.9693
M30
